enum AuthResponsesTypes {
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  SIGNED_UP = 'SIGNED_UP',
  DELETED = 'DELETED',
  PASSWORD_UPDATED = 'PASSWORD_UPDATED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  EMAIL_CHANGED = 'EMAIL_CHANGED',
}

enum EmailResponsesTypes {
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  RESET_PASSWORD_EMAIL_SENT = 'RESET_PASSWORD_EMAIL_SENT',
  VERIFIED_EMAIL_SENT = 'VERIFIED_EMAIL_SENT',
  DELETION_EMAIL_SENT = 'DELETION_EMAIL_SENT',
}

enum FileResponsesTypes {
  SCHEDULED_FOR_CHECK = 'SCHEDULED_FOR_CHECK',
  SHARE_LINK_VERIFIED = 'SHARE_LINK_VERIFIED',
}

export {
  AuthResponsesTypes, EmailResponsesTypes, FileResponsesTypes,
};
