enum AuthResponsesTypes {
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  SIGNED_UP = 'SIGNED_UP',
  DELETED = 'DELETED',
  PASSWORD_UPDATED = 'PASSWORD_UPDATED',
  PASSWORD_RESET = 'PASSWORD_RESET',
}

enum EmailResponsesTypes {
  RESET_PASSWORD_EMAIL_SENT = 'RESET_PASSWORD_EMAIL_SENT',
  VERIFIED_EMAIL_SENT = 'VERIFIED_EMAIL_SENT',
  DELETION_EMAIL_SENT = 'DELETION_EMAIL_SENT',
}

enum FileResponsesTypes {
  SCHEDULED_FOR_CHECK = 'SCHEDULED_FOR_CHECK',
}

export {
  AuthResponsesTypes, EmailResponsesTypes, FileResponsesTypes,
};
